project_id = "ptmeykacgbrsmvcvwrpp"

[functions.api-gateway]
verify_jwt = false

[functions.browser-proxy]
verify_jwt = false

[functions.network-diagnostics]
verify_jwt = false

[functions.send-help-email]
verify_jwt = false

[functions.proxy]
verify_jwt = false

[functions.game-proxy]
verify_jwt = false

[functions.check-embeddable]
verify_jwt = false